USE [master]
GO

/****** Object:  Database [PRODUCTOS]    Script Date: 02/04/2022 13:10:26 ******/
CREATE DATABASE [PRODUCTOS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRODUCTOS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PRODUCTOS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRODUCTOS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PRODUCTOS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRODUCTOS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRODUCTOS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRODUCTOS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRODUCTOS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRODUCTOS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRODUCTOS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRODUCTOS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRODUCTOS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRODUCTOS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRODUCTOS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRODUCTOS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRODUCTOS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRODUCTOS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRODUCTOS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRODUCTOS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRODUCTOS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRODUCTOS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRODUCTOS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRODUCTOS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRODUCTOS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRODUCTOS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRODUCTOS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRODUCTOS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRODUCTOS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PRODUCTOS] SET  MULTI_USER 
GO

ALTER DATABASE [PRODUCTOS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRODUCTOS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRODUCTOS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRODUCTOS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRODUCTOS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRODUCTOS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PRODUCTOS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRODUCTOS] SET  READ_WRITE 
GO

