//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2020RC605_PRACTICA0402
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id { get; set; }
        public Nullable<int> categoriaid { get; set; }
        public string producto { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string estado { get; set; }
    }
}
